### ISSUE TITLE
Minecart Chests cannot be opened properly/at all (Forge 1.20.1)

### ISSUE THREAD

**Issue by goldrat1** [noobanidus/Lootr#320] opened 2024-03-27 02:31 UTC
On 1.20.1 Forge, v0.7.33.81
Right-clicking a Lootr Minecart Chest will cause the container GUI to pop up for a single frame and then disappear. This makes it impossible to take items from generated Minecart Chests.
The carts will evidently still generate the items from the loot table but the GUI doesn't stay open long enough to take them.
Please fix!

**Comment by noobanidus** [comment] 2024-03-27 03:13
Whoops! I'm pretty sure I know the cause of this; let me fix it.

**Comment by noobanidus** [comment] 2024-03-27 03:25
This should be fixed in 0.7.33.82 released on CurseForge just now.

**Closed as completed by noobanidus** 2024-03-27 03:25 UTC
