### ISSUE TITLE
Lootr crashes with byg on a player entering a 1.12.2 server

### ISSUE THREAD

**Issue by Xplodin** [noobanidus/Lootr#182] opened 2023-04-04 06:54 UTC
[crash-2023-04-04_06.51.00-server.txt](https://github.com/noobanidus/Lootr/files/11145528/crash-2023-04-04_06.51.00-server.txt)

suspected mods are byg and lootr

Not much else besides it loads, then once a player enters, they crash the entire server

**Comment by noobanidus** [comment] 2023-04-04 06:55
Assigning to @embeddedt. This looks like a standard MCreator conflict issue. 

EDIT: The original version of BYG was made in MCreator. It's possible that it's just going to be completely incompatible with Lootr, as a warning, but I'm not sure.

**Comment by Xplodin** [comment] 2023-04-04 06:57
Ill remove byg serverside for now, although it works perfect in singleplayer. 
I never knew byg was mcreator until today.

**Comment by embeddedt** [comment] 2023-04-04 13:09
The 1.12 version is MCreator, yes. I will look into it when I have a chance.

**Comment by embeddedt** [comment] 2023-04-07 01:15
I'm not sure if it's really possible to fix this; after deobfuscating the stacktrace it appears that BYG's block simply throws a NPE when you call `destroyBlock` with its position; that doesn't seem like something unreasonable to do from our end.

**Comment by embeddedt** [comment] 2023-04-07 20:43
In theory 0.6.0 will fix this, but I can't reproduce the issue locally so I will need you to try it.

**Comment by noobanidus** [comment] 2023-06-16 02:11
Please comment on this issue and ask for it to be re-opened if it continues after the recent fixes embeddedt has made.

**Closed as completed by noobanidus** 2023-06-16 02:11 UTC
