### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by Baishilalala** [noobanidus/Lootr#197] opened 2023-06-18 11:21 UTC
Game Version: Minecraft 1.20 with Fabric
Used Version: lootr-1.20-0.7.29.69.jar
Bug describe: The minecart with chest in mineshaft can't be opened.

**Comment by noobanidus** [comment] 2023-06-18 11:22
I need a copy of your log file please (server if not single-player).

**Comment by Baishilalala** [comment] 2023-06-18 11:26
[latest.log](https://github.com/noobanidus/Lootr/files/11781308/latest.log)

**Comment by noobanidus** [comment] 2023-06-18 11:27
Thanks! That allows me to see exactly what the issue is. Looking into it now.

**Comment by noobanidus** [comment] 2023-06-18 11:33
Okay, it's fixed in [this version](https://legacy.curseforge.com/minecraft/mc-mods/lootr-fabric/files/4594729) which is awaiting approval on CurseForge. EDIT: Looks like when I copied code, I accidentally copied it from the Forge 1.20 version instead of the Fabric 1.19 version.

**Closed as completed by noobanidus** 2023-06-18 11:33 UTC
