### ISSUE TITLE
Lootr chests fail to load in large pregen world (1.12.2)

### ISSUE THREAD

**Issue by daltonblaha** [noobanidus/Lootr#195] opened 2023-05-31 23:58 UTC
I found while attempting to pregenerate a 50x50 square area of chunks with the Chunk-Pregenerator mod that the lootr chests wouldn't be openable, however this isn't an issue with a smaller pregenerated area (such as a 10x10)

**Comment by noobanidus** [comment] 2023-06-01 00:00
As Lootr works retroactively, I'd strongly recommend disabling or removing Lootr before generating chunks with Chunk Pregenerator, as there are some known conflicts and issues. Once you've generated your world, you can then install Lootr and launch it, and the chests should be converted as they load in.

**Comment by embeddedt** [comment] 2023-06-01 00:02
Note that on 1.12 the `CONVERT_WORLDGEN_INVENTORIES` option (for chests without loot tables) is *not* retroactive, and so you will not be able to convert chests like that using @noobanidus's method.

**Comment by noobanidus** [comment] 2023-06-01 00:03
Ah, I didn't notice this was for 1.12.2. Yes, that would be an issue. You could try using Forge's pre-generation method, which should function properly. 

EDIT: Generally speaking, especially on 1.12.2, I won't ensure compatibility with Chunk Pregenerator in any form as it modifies world generation and can cause issues with things.

**Comment by daltonblaha** [comment] 2023-06-01 17:54
Alright, I'll continue testing to see if reenabling the mod after pregen fixes my issue

**Comment by noobanidus** [comment] 2023-06-16 02:16
Alternately, try the 1.12.2 inbuilt Forge pre-generation method instead. I'll be closing this issue as I can't ensure compatibility with Chunk Pregenerator.

**Closed as completed by noobanidus** 2023-06-16 02:16 UTC

**Comment by Tavisco** [comment] 2023-06-16 17:28
@noobanidus sorry to comment on a closed issue, but I have one question related to this: When running fabric, do you know if I would encounter the same issue when using [Chunky](https://modrinth.com/plugin/chunky) to pregenerate the world? Minecraft version 1.19.2 in my case.

**Comment by noobanidus** [comment] 2023-06-17 05:28
@Tavisco I have no idea. I'd recommend trying it out in single-player to see what happens.

**Comment by Tavisco** [comment] 2023-06-17 22:05
Well, I made a backup of the server world, and ran it there. Happy to report that it worked as intended! The chests were Lootr ones and I could open them without issues :)
