### ISSUE TITLE
Lootr + Embers Rekindled Incompatibility | 1.12.2 Server

### ISSUE THREAD

**Issue by deathhancox** [noobanidus/Lootr#174] opened 2023-03-08 18:37 UTC
I've been going through the error logs for one of my servers and suspected there was an issue between Embers Rekindled and Lootr, so I decided to create a server with just those mods and their dependencies. Sure enough when I tried to start my server (mc 1.12.2) with just those mods and their dependencies it crashed shortly after world gen, I've provided the crash log below:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LootrCore (lootr-1.12.2-0.5.1.jar)
  MixinBooter (!mixinbooter-7.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 3/8/23 11:35 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Quaternion
	at teamroots.embers.util.TurretHelper.<init>(TurretHelper.java:9)
	at teamroots.embers.tileentity.TileEntityTurret.<init>(TileEntityTurret.java:34)
	at teamroots.embers.block.BlockTurret.func_149915_a(BlockTurret.java:49)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at noobanidus.mods.lootr.config.ConfigManager.addUnsafeReplacement(ConfigManager.java:324)
	at noobanidus.mods.lootr.config.ConfigManager.replacement(ConfigManager.java:348)
	at noobanidus.mods.lootr.block.tile.TileTicker.serverTick(TileTicker.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_TileTicker_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.util.vector.Quaternion
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4442801704 bytes (4236 MB) / 6784286720 bytes (6470 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 2 total; -Xmx16384M -Xms6144M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version      | Source                        | Signature                                |
	|:------ |:----------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp         | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mixinbooter | 7.0          | minecraft.jar                 | None                                     |
	| LCHIJA | embers      | 1.19         | EmbersRekindled-1.19.jar      | None                                     |
	| LCHIJA | lootr       | 0.5.1        | lootr-1.12.2-0.5.1.jar        | None                                     |

	Loaded coremods (and transformers): 
LootrCore (lootr-1.12.2-0.5.1.jar)
  
MixinBooter (!mixinbooter-7.0.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by noobanidus** [comment] 2023-03-09 05:18
Thanks! This is a dupe of #171.

**Closed as completed by noobanidus** 2023-03-09 05:18 UTC
