### ISSUE TITLE
Server hang

### ISSUE THREAD

**Issue by Sunekaer** [noobanidus/Lootr#104] opened 2022-05-23 19:18 UTC
Crash log: https://pste.me/v1/paste/tausBkMWI90/raw

Player said the issue stopped when adding "minecraft:overworld" to the location_blacklist variable in the lootr-common.toml config file

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/809

**Comment by noobanidus** [comment] 2022-05-23 22:09
Closing this as a duplicate of #100

**Closed as completed by noobanidus** 2022-05-23 22:09 UTC
